################################################################
#
# Dynamic Configuration for Traefik v2.
#
################################################################

####################################################################
# Dashbord
####################################################################

[api]
  dashboard = true
  insecure = false

[http.routers.secure-api]
  rule = "Host(`traefik.tk`)"
  service = "api@internal"
  middlewares = ["auth"]

[http.middlewares.auth.basicAuth]
  users = [
    "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/",
    "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0",
  ]
